---
title: "Genesis Study:  Session 3"
author: "Genesis 1:20-31"
output:
  tufte::tufte_handout:
    citation_package: natbib
    latex_engine: pdflatex
link-citations: yes
---

```{r setup, include=FALSE}
library(tufte)
# invalidate cache when the tufte version changes
knitr::opts_chunk$set(tidy = FALSE, cache.extra = packageVersion('tufte'))
options(htmltools.dir.version = FALSE)
```

\vspace{0.2 in}

\newcommand{\vn}[1]{\textit{\textbf{#1}}}

\begin{adjustwidth}{}{-2 in}

\large{}

\begin{spacing}{1.7}

\texttt{\vn{20} And God said, "Let the waters swarm with swarms of living 
creatures, and let birds fly above the earth across the expanse of the 
heavens." \vn{21} So God created the great sea creatures and every living 
creature that moves, with which the waters swarm, according to their kinds, 
and every winged bird according to its kind. And God saw that it was 
good. \vn{22} And God blessed them, saying, "Be fruitful and multiply and fill the 
waters in the seas, and let birds multiply on the earth." \vn{23} And there 
was evening and there was morning, the fifth day. \vn{24} And God said, 
"Let the earth bring forth living creatures according to their kinds --- 
livestock and creeping things and beasts of the earth according to their 
kinds." And it was so. \vn{25} And God made the beasts of the earth according 
to their kinds and the livestock according to their kinds, and everything 
that creeps on the ground according to its kind. And God saw that it was 
good. \vn{26} Then God said, "Let us make man in our image, after our 
likeness. And let them have dominion over the fish of the sea and over 
the birds of the heavens and over the livestock and over all the earth and 
over every creeping thing that creeps on the earth." \vn{27} So God created 
man in his own image, in the image of God he created him; male and female 
he created them. \vn{28} And God blessed them. And God said to them, "Be 
fruitful and multiply and fill the earth and subdue it and have dominion 
over the fish of the sea and over the birds of the heavens and over every 
living thing that moves on the earth." \vn{29} And God said, "Behold, I 
have given you every plant yielding seed that is on the face of all the 
earth, and every tree with seed in its fruit. You shall have them for 
food. \vn{30} And to every beast of the earth and to every bird of the heavens 
and to everything that creeps on the earth, everything that has the breath 
of life, I have given every green plant for food." And it was so. \vn{31} And 
God saw everything that he had made, and behold, it was very good. And there 
was evening and there was morning, the sixth day.   (ESV)}

\end{spacing}

\end{adjustwidth}

\vspace{0.3 in}

# Suggestions for Exploration

\large{}

1. Taking the passage as a whole, what patterns do you see?  What similarities 
and differences do you notice between the various parts?  What insights do 
you think might be drawn from these observations?

\vspace{2 in}

2. According to this passage, what does it mean to be human? Is there a sense 
in which the Bible is the story of humanity?  How?  Or if not, why not?

\vspace{2 in}

3. What characteristics of God are reflected in men and in women? How do 
these differences both enhance and complicate marriage relationships?  How do 
men and women complement one another in reflecting God's image?

\vspace{2 in}

4. How would you describe the role God gives humans in this passage? What 
specific things does God mention? How do these things fit into "The 
Big Story"?

\vspace{2 in}

5. The Bible sees Jesus as "the second Adam" (explicitly, Rom 5:12-21, 
1 Cor 15:20-49; implicitly, pretty much everywhere.)  How does contemplating 
Jesus in this way help you have a better understanding of both Jesus' 
mission and "The Big Story"?

\vspace{2 in}

6. In verse 31, God saw all He had made and it was very good. Is this an example
for us of being pleased and satisfied with our accomplishments? Are you ever
robbed of this by the fear  of being proud?


