---
title: "Genesis Study:  Session 4"
author: "Genesis 2:1-3"
output:
  tufte::tufte_handout:
    citation_package: natbib
    latex_engine: pdflatex
link-citations: yes
---

```{r setup, include=FALSE}
library(tufte)
# invalidate cache when the tufte version changes
knitr::opts_chunk$set(tidy = FALSE, cache.extra = packageVersion('tufte'))
options(htmltools.dir.version = FALSE)
```

\vspace{0.2 in}

\newcommand{\vn}[1]{\textit{\textbf{#1}}}

\begin{adjustwidth}{}{-2 in}

\large{}

\begin{spacing}{1.7}

\texttt{\vn{1} Thus the heavens and the earth were finished, and all 
the host of them. \vn{2} And on the seventh day God finished his work 
that he had done, and he rested on the seventh day from all his work 
that he had done. \vn{3} So God blessed the seventh day and made it 
holy, because on it God rested from all his work that he had done in 
creation.   (ESV)}

\end{spacing}

\end{adjustwidth}

\vspace{0.3 in}

# Suggestions for Exploration

\large{}

1. God was able to complete His work.  Is there another time He said it was
finished? What was achieved at that time?

\vspace{2 in}

2. Do you feel you can complete tasks? Can we as humans ever achieve perfection?
Is it healthy to just “let go”?

\vspace{2 in}

3. After such an achievement as creation, what did God do? Is there a rest for
the people of God?  How do we enter it?

\vspace{1.6 in}

4. Read Hebrew 3:7-14.  How does hardening our hearts in unbelief keep us in the
wilderness?  How does believing God give us rest?  How can we keep guard over
our hearts and help others to believe?

\vspace{1.6 in}

5. Consider Hebrews 4:9-16.  Where do we keep our eyes?  How do we come to the
throne of grace? How can we encourage each other to believe?

\vspace{1.6 in}

6. Try to find a passage in the OT that links the Jewish Sabbath directly to 
our passage this week, and explain the logic of the connection.

\vspace{2 in}

7. Consider Exodus 31:13, Deuteronomy 5:15, Isaiah 58:13-14.  What 
do these passages add to your understanding of what God wants the Sabbath to 
mean to His people?  (Try to think in terms of the Sabbath being a sign and 
a blessing.)

\vspace{2 in}

8. Please describe/explain some of Jesus' teaching about the Sabbath. How would
describe a gospel-based view of the Sabbath?

\vspace{2 in}

9. What support can you find in the Bible for changing the Sabbath from the 
seventh day of the week to the first day of the week?

